---
- name: install mariadb
  yum:
    name: mariadb
    state: latest
- name: install mariodb server
  yum:
    name: mariadb-server
    state: latest
- name: install php_mysql server
  yum:
    name: php-mysql
    state: latest
- name: start mariadb
  service:
    name: mariadb
    state: started

